[default]
solc = '0.8.6'
auto_detect_solc = false
src = 'src'
out = 'out'
libs = ['lib']
remappings = ['ds-test/=lib/ds-test/src/']
optimizer = true
optimizer_runs = 200

# See more config options https://github.com/gakonst/foundry/tree/master/config