name: mythril
on:
  push:
  pull_request:

jobs:
  mythril:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Contract
        uses: ./actions/mythril
        id: mythril-contract
        with:
          contract: './src/Contract.sol'
